var postTitle=[],postUrl=[],postPublished=[],postDate=[],postLabels=[],postRecent=[],sortBy="titleasc",numberfeed=0;function elcreativesitemap(b){if("entry" in b.feed){var e=b.feed.entry.length;numberfeed=e;for(var d=ii=0;d<e;d++){for(var a=b.feed.entry[d],f=a.title.$t,c=a.published.$t.substring(0,10),g,h=0;h<a.link.length;h++){if("alternate"==a.link[h].rel){g=a.link[h].href;break}}
var l="";for(h=0;h<a.link.length;h++){if("enclosure"==a.link[h].rel){l=a.link[h].href;break}}
if("category" in a){for(h=0;h<a.category.length;h++){var k=a.category[h].term;var m=k.lastIndexOf(";");-1!=m&&(k=k.substring(0,m));postLabels[ii]=k;postTitle[ii]=f;postDate[ii]=c;postUrl[ii]=g;postPublished[ii]=l;postRecent[ii]=10>d?!0:!1;ii+=1}}}}
sortBy="titledesc";sortPosts(sortBy);sortlabel();displayToc()}
function sortPosts(b){function e(a,c){var b=postTitle[a];postTitle[a]=postTitle[c];postTitle[c]=b;b=postDate[a];postDate[a]=postDate[c];postDate[c]=b;b=postUrl[a];postUrl[a]=postUrl[c];postUrl[c]=b;b=postLabels[a];postLabels[a]=postLabels[c];postLabels[c]=b;b=postPublished[a];postPublished[a]=postPublished[c];postPublished[c]=b;b=postRecent[a];postRecent[a]=postRecent[c];postRecent[c]=b}
for(var d=0;d<postTitle.length-1;d++){for(var a=d+1;a<postTitle.length;a++){"titleasc"==b&&postTitle[d]>postTitle[a]&&e(d,a),"titledesc"==b&&postTitle[d]<postTitle[a]&&e(d,a),"dateoldest"==b&&postDate[d]>postDate[a]&&e(d,a),"datenewest"==b&&postDate[d]<postDate[a]&&e(d,a),"orderlabel"==b&&postLabels[d]>postLabels[a]&&e(d,a)}}}
function sortlabel(){sortBy="orderlabel";sortPosts(sortBy);for(var b=0,e=0;e<postTitle.length;){temp1=postLabels[e];firsti=b;do{b+=1}while(postLabels[b]==temp1);e=b;sortPosts2(firsti,b);if(e>postTitle.length){break}}}
function sortPosts2(b,e){for(var d=b;d<e-1;d++){for(var a=d+1;a<e;a++){if(postTitle[d]>postTitle[a]){var f=d,c=a,g=postTitle[f];postTitle[f]=postTitle[c];postTitle[c]=g;g=postDate[f];postDate[f]=postDate[c];postDate[c]=g;g=postUrl[f];postUrl[f]=postUrl[c];postUrl[c]=g;g=postLabels[f];postLabels[f]=postLabels[c];postLabels[c]=g;g=postPublished[f];postPublished[f]=postPublished[c];postPublished[c]=g;g=postRecent[f];postRecent[f]=postRecent[c];postRecent[c]=g}}}}
function displayToc(){for(var b=0,e=0;e<postTitle.length;){temp1=postLabels[e];document.write("");document.write('<div class="post-archive"><h4>'+temp1+'</h4><ol class="elcsitemap">');firsti=b;do{document.write("<li>"),document.write('<a href="'+postUrl[b]+'">'+postTitle[b]),1==postRecent[b]&&document.write(" - <strong><span>New!</span></strong>"),document.write("</a></li>"),b+=1}while(postLabels[b]==temp1);e=b;document.write("</ol></div>");sortPosts2(firsti,b);if(e>postTitle.length){break}}}
// <script src='/feeds/posts/summary?alt=json-in-script&max-results=9999&callback=elcreativesitemap' type='text/javascript'></script>
